export const RUN_AUTOMATION = 'RUN_AUTOMATION';
export const AUTOMATION_FAILS = 'AUTOMATION_FAILS';
export const STOP_AUTOMATION = 'STOP_AUTOMATION';
export const RUN_INVALID = 'RUN_INVALID';
export const STOP_AUTOMATION_FAILS = 'STOP_AUTOMATION_FAILS';